
from subprocess import check_output

import sys

def list_colors(out):
    reset = check_output(["tput", "sgr0"]).decode()
    reset = r"\[{}\]".format(reset)

    indent = " " * 4

    out.write("# Autogenerated file with strings for all terminal colors\n")
    out.write("\n")
    out.write("class Colors:\n")
    out.write("{}RESET = {}\n".format(indent, repr(reset)))

    for i in range(256):
        col = check_output(["tput", "-T", "xterm-256color", "setab", str(i)]).decode()
        col = r"\[{}\]".format(col)

        out.write("{}BG_{:03} = {}\n".format(indent, i, repr(col)))

    for i in range(256):
        col = check_output(["tput", "-T", "xterm-256color", "setaf", str(i)]).decode()
        col = r"\[{}\]".format(col)

        out.write("{}FG_{:03} = {}\n".format(indent, i, repr(col)))

if __name__ == "__main__":
    list_colors(sys.stdout)
